version: "3"
services:
    minio:
        image: quay.io/minio/minio:RELEASE.2021-09-03T03-56-13Z
        command: server --console-address ":9001" /var/lib/minio-data
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
        volumes:
            - .minio-data:/var/lib/minio-data
